import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ysfik's Portfolio",
  description:
    "Generated by create next appHello, I'm Fikri Nurdiansyah, but you can call me Ysfik. As a Fullstack Web Developer, I'm dedicated to turning visions into reality. Let's collaborate and unleash the full potential of your ideas.",
  authors: { name: "Fikri Nurdiansyah", url: "https://ysfik.my.id" },
  keywords: [
    "Ysfik",
    "portfolio",
    "web developer",
    "fullstack",
    "freelancer",
    "innovation",
    "blockchain developer",
  ],
  icons: "../../public/Favicon.svg",
  publisher: "Fikri Nurdiansyah",
  category: "Portfolio",
  creator: "Fikri Nurdiansyah",
  alternates: {
    canonical: "https://ysfik.my.id",
  },
  applicationName: "Ysfik Portfolio",
  metadataBase: new URL("https://ysfik.my.id"),
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
